export interface CatalogItem {
  id: string;
  name: string;
  type: "hotel" | "motel" | "auberge" | "residence";
  city: string;
  region: string;
  price: number;
  currency: string;
  rating: number;
  reviews: number;
  sponsored: boolean;
  amenities: string[];
  summary: string;
}

// Static public catalog (mirrors the app's accommodation listings, without image assets).
export const accommodations: CatalogItem[] = [
  {
    id: "1",
    name: "Hôtel Fouta Djallon",
    type: "hotel",
    city: "Labé",
    region: "Fouta Djallon",
    price: 450000,
    currency: "GNF",
    rating: 4.7,
    reviews: 124,
    sponsored: true,
    amenities: ["WiFi", "Restaurant", "Piscine", "Parking", "Bar", "Climatisation"],
    summary: "Hôtel moderne au cœur des montagnes du Fouta Djallon, restaurant gastronomique et piscine panoramique.",
  },
  {
    id: "2",
    name: "Résidence Nimba",
    type: "residence",
    city: "N'Zérékoré",
    region: "Guinée Forestière",
    price: 380000,
    currency: "GNF",
    rating: 4.5,
    reviews: 89,
    sponsored: true,
    amenities: ["WiFi", "Climatisation", "Sécurité 24h/24", "Parking", "Jardin", "Blanchisserie"],
    summary: "Appartements meublés près du Mont Nimba, idéaux pour les séjours prolongés.",
  },
  {
    id: "3",
    name: "Auberge Konkouré",
    type: "auberge",
    city: "Kindia",
    region: "Basse Guinée",
    price: 150000,
    currency: "GNF",
    rating: 4.2,
    reviews: 56,
    sponsored: false,
    amenities: ["WiFi", "Petit-déjeuner", "Parking", "Terrasse"],
    summary: "Auberge conviviale à Kindia, proche des chutes et de la nature environnante.",
  },
  {
    id: "4",
    name: "Motel Badiar",
    type: "motel",
    city: "Boké",
    region: "Basse Guinée",
    price: 220000,
    currency: "GNF",
    rating: 4.0,
    reviews: 41,
    sponsored: false,
    amenities: ["WiFi", "Parking", "Climatisation", "Restaurant"],
    summary: "Étape pratique à Boké pour les voyageurs d'affaires et de transit.",
  },
  {
    id: "5",
    name: "Hôtel Soumba",
    type: "hotel",
    city: "Faranah",
    region: "Haute Guinée",
    price: 320000,
    currency: "GNF",
    rating: 4.3,
    reviews: 73,
    sponsored: false,
    amenities: ["WiFi", "Restaurant", "Parking", "Climatisation", "Bar"],
    summary: "Hôtel confortable à Faranah avec restaurant et service attentif.",
  },
  {
    id: "6",
    name: "Résidence Kakoulima",
    type: "residence",
    city: "Conakry",
    region: "Conakry",
    price: 520000,
    currency: "GNF",
    rating: 4.8,
    reviews: 156,
    sponsored: true,
    amenities: ["WiFi", "Piscine", "Salle de sport", "Parking", "Sécurité 24h/24", "Climatisation"],
    summary: "Résidence premium à Conakry avec piscine, salle de sport et sécurité permanente.",
  },
  {
    id: "7",
    name: "Auberge Tinkisso",
    type: "auberge",
    city: "Dabola",
    region: "Haute Guinée",
    price: 130000,
    currency: "GNF",
    rating: 4.1,
    reviews: 34,
    sponsored: false,
    amenities: ["WiFi", "Petit-déjeuner", "Parking"],
    summary: "Petite auberge chaleureuse à Dabola, à prix accessible.",
  },
  {
    id: "8",
    name: "Motel Kankan",
    type: "motel",
    city: "Kankan",
    region: "Haute Guinée",
    price: 200000,
    currency: "GNF",
    rating: 4.0,
    reviews: 48,
    sponsored: false,
    amenities: ["WiFi", "Parking", "Climatisation"],
    summary: "Motel simple et fonctionnel au centre de Kankan.",
  },
  {
    id: "9",
    name: "Hôtel Sily",
    type: "hotel",
    city: "Labé",
    region: "Fouta Djallon",
    price: 290000,
    currency: "GNF",
    rating: 4.4,
    reviews: 67,
    sponsored: false,
    amenities: ["WiFi", "Restaurant", "Parking", "Bar", "Climatisation"],
    summary: "Hôtel central à Labé, bon rapport qualité-prix.",
  },
  {
    id: "10",
    name: "Résidence Loos",
    type: "residence",
    city: "Conakry",
    region: "Conakry",
    price: 480000,
    currency: "GNF",
    rating: 4.6,
    reviews: 112,
    sponsored: true,
    amenities: ["WiFi", "Vue mer", "Parking", "Climatisation", "Sécurité 24h/24"],
    summary: "Résidence avec vue sur les îles de Loos, à Conakry.",
  },
];
