// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-accommodations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/catalog.ts
var accommodations = [
  {
    id: "1",
    name: "H\xF4tel Fouta Djallon",
    type: "hotel",
    city: "Lab\xE9",
    region: "Fouta Djallon",
    price: 45e4,
    currency: "GNF",
    rating: 4.7,
    reviews: 124,
    sponsored: true,
    amenities: ["WiFi", "Restaurant", "Piscine", "Parking", "Bar", "Climatisation"],
    summary: "H\xF4tel moderne au c\u0153ur des montagnes du Fouta Djallon, restaurant gastronomique et piscine panoramique."
  },
  {
    id: "2",
    name: "R\xE9sidence Nimba",
    type: "residence",
    city: "N'Z\xE9r\xE9kor\xE9",
    region: "Guin\xE9e Foresti\xE8re",
    price: 38e4,
    currency: "GNF",
    rating: 4.5,
    reviews: 89,
    sponsored: true,
    amenities: ["WiFi", "Climatisation", "S\xE9curit\xE9 24h/24", "Parking", "Jardin", "Blanchisserie"],
    summary: "Appartements meubl\xE9s pr\xE8s du Mont Nimba, id\xE9aux pour les s\xE9jours prolong\xE9s."
  },
  {
    id: "3",
    name: "Auberge Konkour\xE9",
    type: "auberge",
    city: "Kindia",
    region: "Basse Guin\xE9e",
    price: 15e4,
    currency: "GNF",
    rating: 4.2,
    reviews: 56,
    sponsored: false,
    amenities: ["WiFi", "Petit-d\xE9jeuner", "Parking", "Terrasse"],
    summary: "Auberge conviviale \xE0 Kindia, proche des chutes et de la nature environnante."
  },
  {
    id: "4",
    name: "Motel Badiar",
    type: "motel",
    city: "Bok\xE9",
    region: "Basse Guin\xE9e",
    price: 22e4,
    currency: "GNF",
    rating: 4,
    reviews: 41,
    sponsored: false,
    amenities: ["WiFi", "Parking", "Climatisation", "Restaurant"],
    summary: "\xC9tape pratique \xE0 Bok\xE9 pour les voyageurs d'affaires et de transit."
  },
  {
    id: "5",
    name: "H\xF4tel Soumba",
    type: "hotel",
    city: "Faranah",
    region: "Haute Guin\xE9e",
    price: 32e4,
    currency: "GNF",
    rating: 4.3,
    reviews: 73,
    sponsored: false,
    amenities: ["WiFi", "Restaurant", "Parking", "Climatisation", "Bar"],
    summary: "H\xF4tel confortable \xE0 Faranah avec restaurant et service attentif."
  },
  {
    id: "6",
    name: "R\xE9sidence Kakoulima",
    type: "residence",
    city: "Conakry",
    region: "Conakry",
    price: 52e4,
    currency: "GNF",
    rating: 4.8,
    reviews: 156,
    sponsored: true,
    amenities: ["WiFi", "Piscine", "Salle de sport", "Parking", "S\xE9curit\xE9 24h/24", "Climatisation"],
    summary: "R\xE9sidence premium \xE0 Conakry avec piscine, salle de sport et s\xE9curit\xE9 permanente."
  },
  {
    id: "7",
    name: "Auberge Tinkisso",
    type: "auberge",
    city: "Dabola",
    region: "Haute Guin\xE9e",
    price: 13e4,
    currency: "GNF",
    rating: 4.1,
    reviews: 34,
    sponsored: false,
    amenities: ["WiFi", "Petit-d\xE9jeuner", "Parking"],
    summary: "Petite auberge chaleureuse \xE0 Dabola, \xE0 prix accessible."
  },
  {
    id: "8",
    name: "Motel Kankan",
    type: "motel",
    city: "Kankan",
    region: "Haute Guin\xE9e",
    price: 2e5,
    currency: "GNF",
    rating: 4,
    reviews: 48,
    sponsored: false,
    amenities: ["WiFi", "Parking", "Climatisation"],
    summary: "Motel simple et fonctionnel au centre de Kankan."
  },
  {
    id: "9",
    name: "H\xF4tel Sily",
    type: "hotel",
    city: "Lab\xE9",
    region: "Fouta Djallon",
    price: 29e4,
    currency: "GNF",
    rating: 4.4,
    reviews: 67,
    sponsored: false,
    amenities: ["WiFi", "Restaurant", "Parking", "Bar", "Climatisation"],
    summary: "H\xF4tel central \xE0 Lab\xE9, bon rapport qualit\xE9-prix."
  },
  {
    id: "10",
    name: "R\xE9sidence Loos",
    type: "residence",
    city: "Conakry",
    region: "Conakry",
    price: 48e4,
    currency: "GNF",
    rating: 4.6,
    reviews: 112,
    sponsored: true,
    amenities: ["WiFi", "Vue mer", "Parking", "Climatisation", "S\xE9curit\xE9 24h/24"],
    summary: "R\xE9sidence avec vue sur les \xEEles de Loos, \xE0 Conakry."
  }
];

// src/lib/mcp/tools/search-accommodations.ts
var search_accommodations_default = defineTool({
  name: "search_accommodations",
  title: "Rechercher des h\xE9bergements",
  description: "Rechercher les h\xE9bergements du catalogue Simandou S\xE9jour par ville, r\xE9gion, type ou prix maximum.",
  inputSchema: {
    query: z.string().optional().describe("Texte libre (nom, ville, r\xE9gion, \xE9quipement)."),
    city: z.string().optional().describe("Ville, ex. Conakry."),
    type: z.enum(["hotel", "motel", "auberge", "residence"]).optional().describe("Type d'h\xE9bergement."),
    maxPrice: z.number().optional().describe("Prix maximum par nuit en GNF."),
    limit: z.number().optional().describe("Nombre maximum de r\xE9sultats (d\xE9faut 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, city, type, maxPrice, limit }) => {
    const q = query?.trim().toLowerCase();
    const results = accommodations.filter((a) => type ? a.type === type : true).filter((a) => city ? a.city.toLowerCase().includes(city.toLowerCase()) : true).filter((a) => typeof maxPrice === "number" ? a.price <= maxPrice : true).filter(
      (a) => q ? [a.name, a.city, a.region, a.summary, ...a.amenities].join(" ").toLowerCase().includes(q) : true
    ).sort((a, b) => Number(b.sponsored) - Number(a.sponsored) || b.rating - a.rating).slice(0, Math.max(1, Math.min(limit ?? 10, 50)));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-accommodation.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_accommodation_default = defineTool2({
  name: "get_accommodation",
  title: "D\xE9tail d'un h\xE9bergement",
  description: "Obtenir la fiche d\xE9taill\xE9e d'un h\xE9bergement de Simandou S\xE9jour \xE0 partir de son identifiant.",
  inputSchema: { id: z2.string().describe(`Identifiant de l'h\xE9bergement, ex. "1".`) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const item = accommodations.find((a) => a.id === id);
    if (!item) {
      return { content: [{ type: "text", text: `Aucun h\xE9bergement avec l'identifiant ${id}.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(item, null, 2) }],
      structuredContent: { accommodation: item }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Mon profil",
  description: "R\xE9cup\xE9rer le profil Simandou S\xE9jour de l'utilisateur connect\xE9 (nom, langue, points, pr\xE9f\xE9rences).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name, bio, phone, language, reward_points, badges, preferences, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Aucun profil trouv\xE9 pour cet utilisateur." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_notifications_default = defineTool4({
  name: "list_my_notifications",
  title: "Mes notifications",
  description: "Lister les notifications de l'utilisateur connect\xE9, les plus r\xE9centes d'abord.",
  inputSchema: {
    unreadOnly: z3.boolean().optional().describe("Ne renvoyer que les notifications non lues."),
    limit: z3.number().optional().describe("Nombre maximum de notifications (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unreadOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("notifications").select("id, title, message, type, link, read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.max(1, Math.min(limit ?? 20, 100)));
    if (unreadOnly) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-reviews.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_reviews_default = defineTool5({
  name: "list_my_reviews",
  title: "Mes avis",
  description: "Lister les avis publi\xE9s par l'utilisateur connect\xE9 sur les h\xE9bergements.",
  inputSchema: {
    limit: z4.number().optional().describe("Nombre maximum d'avis (d\xE9faut 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("reviews").select("id, accommodation_id, title, comment, rating, verified_stay, host_response, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.max(1, Math.min(limit ?? 20, 100)));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-review.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_review_default = defineTool6({
  name: "create_review",
  title: "Publier un avis",
  description: "Publier un avis (titre, commentaire, note sur 5) sur un h\xE9bergement au nom de l'utilisateur connect\xE9.",
  inputSchema: {
    accommodationId: z5.string().describe(`Identifiant de l'h\xE9bergement, ex. "1".`),
    title: z5.string().describe("Titre court de l'avis."),
    comment: z5.string().describe("Contenu de l'avis."),
    rating: z5.number().describe("Note de 1 \xE0 5.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ accommodationId, title, comment, rating }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const note = Math.round(rating);
    if (note < 1 || note > 5) {
      return { content: [{ type: "text", text: "La note doit \xEAtre comprise entre 1 et 5." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("reviews").insert({
      user_id: ctx.getUserId(),
      accommodation_id: accommodationId,
      title: title.trim(),
      comment: comment.trim(),
      rating: note
    }).select("id, accommodation_id, title, rating, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null, null, 2) }],
      structuredContent: { review: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lnntdyhrdlaxoyhrriox";
var mcp_default = defineMcp({
  name: "simandou-sejour",
  title: "simandou-sejour",
  version: "0.1.0",
  instructions: "Outils de Simandou S\xE9jour, la plateforme de r\xE9servation d'h\xE9bergements en Guin\xE9e. Utilisez search_accommodations et get_accommodation pour explorer le catalogue public, et get_my_profile, list_my_notifications, list_my_reviews et create_review pour les donn\xE9es de l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_accommodations_default,
    get_accommodation_default,
    get_my_profile_default,
    list_my_notifications_default,
    list_my_reviews_default,
    create_review_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
